[2024-08-27T21:13:25.815+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: group_dag.transforms manual__2024-08-27T21:12:12.950505+00:00 [queued]>
[2024-08-27T21:13:25.824+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: group_dag.transforms manual__2024-08-27T21:12:12.950505+00:00 [queued]>
[2024-08-27T21:13:25.824+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-08-27T21:13:25.824+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-08-27T21:13:25.824+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-08-27T21:13:25.838+0000] {taskinstance.py:1383} INFO - Executing <Task(SubDagOperator): transforms> on 2024-08-27 21:12:12.950505+00:00
[2024-08-27T21:13:25.846+0000] {standard_task_runner.py:55} INFO - Started process 2768 to run task
[2024-08-27T21:13:25.850+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'group_dag', 'transforms', 'manual__2024-08-27T21:12:12.950505+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/course_group_dag.py', '--cfg-path', '/tmp/tmp086221je']
[2024-08-27T21:13:25.850+0000] {standard_task_runner.py:83} INFO - Job 89: Subtask transforms
[2024-08-27T21:13:25.915+0000] {task_command.py:376} INFO - Running <TaskInstance: group_dag.transforms manual__2024-08-27T21:12:12.950505+00:00 [running]> on host 481ff13a8537
[2024-08-27T21:13:25.995+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=group_dag
AIRFLOW_CTX_TASK_ID=transforms
AIRFLOW_CTX_EXECUTION_DATE=2024-08-27T21:12:12.950505+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-27T21:12:12.950505+00:00
[2024-08-27T21:13:25.996+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-08-27T21:13:26.027+0000] {subdag.py:171} INFO - Created DagRun: scheduled__2024-08-27T21:12:12.950505+00:00
[2024-08-27T21:17:23.414+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-08-27T21:17:23.417+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 2768. PIDs of all processes in the group: [2768]
[2024-08-27T21:17:23.417+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 2768
[2024-08-27T21:17:23.417+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-27T21:17:23.429+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 211, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1564, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-08-27T21:17:23.433+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=group_dag, task_id=transforms, execution_date=20240827T211212, start_date=20240827T211325, end_date=20240827T211723
[2024-08-27T21:17:23.447+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 89 for task transforms ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(group_dag, transforms, manual__2024-08-27T21:12:12.950505+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'transforms', 'dag_id': 'group_dag', 'run_id': 'manual__2024-08-27T21:12:12.950505+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 8, 27, 21, 13, 25, 816410, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 8, 27, 21, 17, 23, 432912, tzinfo=Timezone('UTC')), 'duration': 237}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 2768)
[2024-08-27T21:17:23.469+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2768, status='terminated', exitcode=1, started='21:13:25') (2768) terminated with exit code 1
