[2024-08-28T22:12:22.383+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-28T22:12:22.394+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info scheduled__2024-08-27T00:00:00+00:00 [queued]>
[2024-08-28T22:12:22.394+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T22:12:22.394+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2024-08-28T22:12:22.394+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T22:12:22.411+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): print_es_info> on 2024-08-27 00:00:00+00:00
[2024-08-28T22:12:22.422+0000] {standard_task_runner.py:55} INFO - Started process 110 to run task
[2024-08-28T22:12:22.425+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'elastic_dag', 'print_es_info', 'scheduled__2024-08-27T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/course_elastic_dag.py', '--cfg-path', '/tmp/tmphekyxsq2']
[2024-08-28T22:12:22.427+0000] {standard_task_runner.py:83} INFO - Job 155: Subtask print_es_info
[2024-08-28T22:12:22.508+0000] {task_command.py:376} INFO - Running <TaskInstance: elastic_dag.print_es_info scheduled__2024-08-27T00:00:00+00:00 [running]> on host 15e03dfad604
[2024-08-28T22:12:22.593+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=elastic_dag
AIRFLOW_CTX_TASK_ID=print_es_info
AIRFLOW_CTX_EXECUTION_DATE=2024-08-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-27T00:00:00+00:00
[2024-08-28T22:12:22.604+0000] {base.py:71} INFO - Using connection ID 'elastic_default' for task execution.
[2024-08-28T22:12:22.604+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/course_elastic_dag.py", line 8, in _print_es_info
    hook = ElasticHook()
  File "/opt/airflow/plugins/hooks/elastic/elastic_hook.py", line 14, in __init__
    if conn.hosts:
AttributeError: 'Connection' object has no attribute 'hosts'
[2024-08-28T22:12:22.613+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=elastic_dag, task_id=print_es_info, execution_date=20240827T000000, start_date=20240828T221222, end_date=20240828T221222
[2024-08-28T22:12:22.624+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 155 for task print_es_info ('Connection' object has no attribute 'hosts'; 110)
[2024-08-28T22:12:22.677+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-08-28T22:12:22.698+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
